spring:
  datasource:
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://localhost/LogisticsPlatform?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      initial-size: 3
      min-idle: 3
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: "SELECT NOW()"
      test-on-borrow: false
      test-on-return: false
  main:
    banner-mode: "off"
  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: "NON_NULL"
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  http:
    encoding:
      force: true
  freemarker:
    check-template-location: false
mybatis:
  config-location: classpath:config/mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:config/sqlmap/*.xml
  type-aliases-package: org.lijun.domain